/* O comentário em MySQL é # */

/* Modelagem Básica OU CONCEITUAL - 
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS  */

CLIENTE

NOME - CARACTERES (+/- 30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - EXECUTADA PELO AD => Administrador de Dados */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA => Administrador do BANCO de dados OU AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLO;

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BÁSICA DE INSERÇÃO - INSERT INTO TABELAS... */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - DESCREVENDO AS COLUNAS */

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('LIILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */
/* o número INT 99999999999 não é aceito pois está fora do range aceitado pelo MySQL */

INSERT INTO CLIENTE VALUES('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '548556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'), ('CARLA', 'F', 'CARLA@TERATI.COM.BR', 7745828, '66587458', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/* O COMANDO SELECT 
SELEÇÃO, PROJEÇÃO E JUNÇÃO
*/

/* PROJEÇÕES */

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

/* ALTERANDO A EXIBIÇÃO DE NOME PARA CLIENTE */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

/* PODEMOS DEFINIR A NOSSA ORDEM */

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;

/* PODEMOS MISTURAR O SELECT COM FUNÇÕES */

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADÊMICOS - NAO USAR EM UM AMBIENTE REAL */

SELECT * FROM CLIENTE;

/* TABELA ERRADA (FALTA , DO EMAIL) - NAO DIGITE DIRETAMENTE NO BANCO */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30)
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* FILTRANDO - EM LINHAS (REGISTROS) => WHERE */

SELECT NOME, SEXO  FROM CLIENTE
WHERE SEXO = 'M';

/* O FILTRO NAO TEM RELACAO COM A SELECAO */

SELECT NOME, ENDERECO  FROM CLIENTE
WHERE SEXO = 'F';

/* MOSTRA VAZIO POIS DEVEMOS UTILIZAR O LIKE */

SELECT NOME, SEXO  FROM CLIENTE
WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE - NAO FUNCIONA POIS PRECISAMOS DO CARACTER CORINGA */

SELECT NOME, SEXO  FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> COMEÇA COM QUALQUER COISA E TERMINA COM RJ*/

SELECT NOME, SEXO  FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

/* NO INICIO */

SELECT NOME, SEXO, ENDERECO  FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

/* NO MEIO */

SELECT NOME, SEXO, ENDERECO  FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

